---
- name: Open NFS ports in firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - nfs
    - mountd
    - rpc-bind
  notify: Reload firewalld

- name: Apply firewall changes
  systemd:
    name: firewalld
    state: restarted
    enabled: yes

